# mkinitcpio configuration file
# NeonPulse OS - linux-zen kernel

MODULES=(nvidia nvidia_modeset nvidia_uvm nvidia_drm amdgpu radeon nouveau i915)

BINARIES=(btrfsck fsck.btrfs)

FILES=()

HOOKS=(base udev autodetect modconf block filesystems keyboard fsck)

COMPRESSION="zstd"
COMPRESSION_OPTIONS=(-3)
